[package]
name = "lexactivator"
version = "3.0.0"
edition = "2021"
description = "LexActivator SDK for Rust"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
cfg-if = "1.0.0"

[[example]]
name="license-activation"
crate-type=["bin"]